services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - drupal-data:/var/lib/mysql
    ports:
      - "3307:3306"

  drupal:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: drupal_app
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
    volumes:
      - .:/var/www/html

volumes:
  drupal-data:
  drupal-files:
